name: Build Amd64 Offline Image
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Install cloud-kernel and run
        env:
          ak: ${{ secrets.AK }}
          sk: ${{ secrets.SK }}
          token: ${{ secrets.MARKETCTL }}
        run: |
          CLOUD_URL=$(curl -LsSf https://api.github.com/repos/sealyun/cloud-kernel/releases/latest | jq -r ".assets[0].browser_download_url")
          wget -c $CLOUD_URL -O cloud-kernel && chmod +x cloud-kernel
          export PATH=${PATH}:$(pwd)
          cloud-kernel run --ak $ak --sk $sk --marketctl $token
